workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Install Flutter
        script: |
          flutter create .
          flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
